name: Deploy staging

on:
  push:
    branches:
      - staging
  repository_dispatch:
    types:
      - update_draft

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging
      - run: cat README.md
